apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-template-hpa
  namespace: product-template
  labels:
    app: product-template
    version: 0.0.1
    backstage.io/kubernetes-id: product-template
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: product-template
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75