apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-app-07-hpa
  namespace: go-app-07
  labels:
    app: go-app-07
    version: 0.0.1
    backstage.io/kubernetes-id: go-app-07
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: go-app-07
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75