---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-app-07
resources:
  - namespace.yaml
  - go-app-07-quota.yaml
  - go-app-07-deployment.yaml
  - go-app-07-service.yaml
  - go-app-07-vs.yaml
  - go-app-07-hpa.yaml
  - go-app-07-dns-record.yaml