apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-app-02-hpa
  namespace: go-app-02
  labels:
    app: go-app-02
    version: 0.0.1
    backstage.io/kubernetes-id: go-app-02
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: go-app-02
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75