---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-app-02
resources:
  - namespace.yaml
  - go-app-02-quota.yaml
  - go-app-02-deployment.yaml
  - go-app-02-service.yaml
  - go-app-02-vs.yaml
  - go-app-02-hpa.yaml
  - crossplane-rt53.yaml