apiVersion: api.pauloponciano.digital/v1alpha1
kind: CustomRecord
metadata:
  name: go-app-01
  namespace: go-app-01
  labels:
    app: go-app-01
    backstage.io/kubernetes-id: go-app-01
spec:
  compositionSelector:
    matchLabels:
      service: route53
      domain: pauloponciano.digital
  resourceConfig:
    providerConfigName: aws
    record: go-app-01
    region: us-west-2
