---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-app-01
resources:
  - namespace.yaml
  - go-app-01-quota.yaml
  - go-app-01-deployment.yaml
  - go-app-01-service.yaml
  - go-app-01-vs.yaml
  - go-app-01-hpa.yaml
  - go-app-01-dns-record.yaml