apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: v1.17.1
    - repoURL: https://github.com/pegasus-idp/gitops
      targetRevision: HEAD
      path: deployed_apps/crossplane
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true