apiVersion: api.pauloponciano.digital/v1alpha1
kind: CustomRecord
metadata:
  name: product-catalog
  namespace: product-catalog
  labels:
    app: product-catalog
    backstage.io/kubernetes-id: product-catalog
spec:
  compositionSelector:
    matchLabels:
      service: route53
      domain: pauloponciano.digital
  resourceConfig:
    providerConfigName: aws
    record: product-catalog
    region: us-east-2
