apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-catalog-hpa
  namespace: product-catalog
  labels:
    app: product-catalog
    version: 0.0.1
    backstage.io/kubernetes-id: product-catalog
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: product-catalog
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75