apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws
  namespace: crossplane-system
spec:
  assumeRoleWithWebIdentity:
    roleARN: "arn:aws:iam::651644924182:role/crossplane-route53-access"
  credentials:
    source: InjectedIdentity