---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: go-app-04-quota
  namespace: go-app-04
  labels:
    kubernetes.io/metadata.name: go-app-04
    backstage.io/kubernetes-id: go-app-04
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi