apiVersion: api.pauloponciano.digital/v1alpha1
kind: CustomRecord
metadata:
  name: go-app-04
  namespace: go-app-04
  labels:
    app: go-app-04
    backstage.io/kubernetes-id: go-app-04
spec:
  compositionSelector:
    matchLabels:
      service: route53
      domain: pauloponciano.digital
  resourceConfig:
    providerConfigName: aws
    record: go-app-04
    region: us-west-2
